export const GET_FACILITIES = 'GET_FACILITIES';
export const ADD_FACILITIES = 'ADD_FACILITIES';
export const DELETE_FACILITIES = 'DELETE_FACILITIES';
export const UPDATE_FACILITIES = 'UPDATE_FACILITIES'
export const LOADING_FACILITIES = 'LOADING_FACILITIES'  



export const LOADING_PRODUCTS = 'LOADING_PRODUCTS';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const EDIT_PRODUCTS = 'EDIT_PRODUCTS';
export const DELETE_PRODUCTS = 'DELETE_PRODUCTS';
export const ERROR_PRODUCTS = 'ERROR_PRODUCTS';

export const LOADING_SUBCATEGORY = 'LOADING_SUBCATEGORY';
export const GET_SUBCATEGORY = 'GET_SUBCATEGORY';
export const ADD_SUBCATEGORY = 'ADD_SUBCATEGORY';
export const EDIT_SUBCATEGORY = 'EDIT_SUBCATEGORY';
export const DELETE_SUBCATEGORY = 'DELETE_SUBCATEGORY';
export const ERROR_SUBCATEGORY = 'ERROR_SUBCATEGORY';
export const FILTER_SUBCATEGORY ='FILTER_SUBCATEGORY'

export const LOADING_ORGANIC = 'LOADING_ORGANIC';
export const GET_ORGANIC = 'GET_ORGANIC';
export const ADD_ORGANIC = 'ADD_ORGANIC';
export const EDIT_ORGANIC = 'EDIT_ORGANIC';
export const DELETE_ORGANIC = 'DELETE_ORGANIC';
export const ERROR_ORGANIC = 'ERROR_ORGANIC';


export const ADD_REVIEW = 'ADD_REVIEW'
export const GET_REVIEW = 'GET_REVIEW'